kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world
- name: build
  image: node
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - npm install
  - npm test
- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde
  trigger:
  branch:
  - master
